language: node_js
node_js:
  - "stable"
services:
 - postgres
env: 
  global: 
    - DATABASE_URL=postgresql://postgres:@localhost:5432/mydiarydbtest
sudo: false # makes tests faster
install:
  - npm install
before_script:
  - psql -c 'create database mydiarydbtest;' -U postgres
  - npm run db
script: npm run pretest
after_success:
  - npm run coveralls
cache:
  directories:
    - "node_modules"