language: node_js
node_js:
  - "8"
services:
 - postgres
addons:
  postgresql: "11.2"
env: 
  global: 
    - DATABASE_URL=postgresql://postgres:@localhost:5432/mydiarydbtest
sudo: false # makes tests faster
install:
  - npm install
before_script:
  - psql -c 'drop database if exists mydiarydbtest;' -U postgres
  - psql -c 'create database mydiarydbtest;' -U postgres
  - npm run db
  - npm run pretest
script: npm run test
after_success:
  - npm run coveralls
cache:
  directories:
    - "node_modules"