language: node_js
node_js:
  - "stable"
env: 
  global: 
    - JWT_AUTH_TOKEN_TEST=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhc2hpcmlAcGlvY29kZS5jb20iLCJmdWxsbmFtZSI6Ikl5YW51IGFzaGlyaSIsImlhdCI6MTUzMjU2MjQxNCwiZXhwIjoxNTMyNzM1MjE0fQ.BXkEk2-IB12FucAznVfrj-wk9bUs0560OVSmddX1FaM
sudo: false # makes tests faster
install:
  - npm install
script: npm run pretest
after_success:
  - npm run coveralls
cache:
  directories:
    - "node_modules"